# syntax=docker/dockerfile:1

FROM amazoncorretto:17-al2023-jdk

# Switch to root user
USER root

#install_mongo_drivers

ADD mongo.repo /etc/yum.repos.d/mongodb-org.repo

# Set the working directory

WORKDIR /root

#install mongo drivers

# Install required packages and MongoDB shell/tools in a single RUN command
RUN yum update -y && \
    yum install -y \
        procps \
        xorg-x11-fonts-75dpi \
        xorg-x11-fonts-Type1 \
        mongodb-mongosh-shared-openssl3 \
        mongodb-org-tools && \
    yum clean all && \
    rm -rf /var/cache/yum

RUN ln -sf /usr/share/zoneinfo/PST8PDT /etc/localtime

#newrelic

RUN mkdir -p /usr/local/newrelic

ADD ./newrelic.jar /usr/local/newrelic/newrelic.jar

#install_packages
#RUN yum -y install xorg-x11-fonts-75dpi xorg-x11-fonts-Type1 -y 

ENTRYPOINT ["/bin/sh"]
