
# Pull lightweight Alpine image

FROM amazoncorretto:17-al2023-jdk

# Switch to root user

USER root

#patch_update

WORKDIR /root

RUN yum update -y && \

    yum install -y wget tar gzip cups-libs dbus-glib cairo libXext libSM libXrender libX11 libjpeg openssl xorg-x11-fonts-75dpi xorg-x11-fonts-Type1 procps tomcat9 ImageMagick  && \

    rm -rf /var/cache/dnf/* && \

    dnf clean all

RUN cp /usr/bin/convert /usr/bin/imconvert

# Install wkhtmltopdf

RUN wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox-0.12.6-1.amazonlinux2.x86_64.rpm && \

    rpm -ivh wkhtmltox-0.12.6-1.amazonlinux2.x86_64.rpm && \

    rm -rf wkhtmltox-0.12.6-1.amazonlinux2.x86_64.rpm

# Install LibreOffice

COPY LibreOffice_6.0.2.1_Linux_x86-64_rpm.tar.gz /root/

RUN tar -xvf LibreOffice_6.0.2.1_Linux_x86-64_rpm.tar.gz && \

    rm -rf LibreOffice_6.0.2.1_Linux_x86-64_rpm.tar.gz && \

    yum localinstall -y LibreOffice_6.0.2.1_Linux_x86-64_rpm/RPMS/*.rpm && \

    rm -rf LibreOffice_6.0.2.1_Linux_x86-64_rpm


# Create directory structure

RUN mkdir -p /app/data/project_files/{files,batch,temp,archive} \

             /app/data/{spellcheck,tomcat_temp,user_profiles} \

             /app/logs/tomcat/dump \

             /var/cache/tomcat/temp

# Copy Tomcat configuration

COPY config /usr/local/tomcat/conf

#set_PDT

RUN ln -sf /usr/share/zoneinfo/PST8PDT /etc/localtime

#newrelic

RUN mkdir -p /usr/local/newrelic

ADD newrelic.jar /usr/local/newrelic/newrelic.jar

# Deploy application

RUN mkdir -p /rfpserver/rfpserver

COPY deploy/*.properties deploy/*.xml /rfpserver/rfpserver/WEB-INF/classes/

#reverting_back_to_tomcat_directory

WORKDIR /usr/local/tomcat/

#setting_entrypoint_as_shell;can_be_overridden_via_k8s

ENTRYPOINT ["/bin/sh"]
